import { test, expect } from '@playwright/test';

test.use({
  viewport: {
    height: 1050,
    width: 1680
  }
});

test('test', async ({ page }) => {
  await page.goto('http://3.80.32.182:3000/');
  await page.getByPlaceholder('Enter your email').click();
  await page.getByPlaceholder('Enter your email').fill('gp2_test+12@twilightitsolutions.com');
  await page.getByPlaceholder('Enter your Password').click();
  await page.getByPlaceholder('Enter your Password').fill('Am@zing#Grace3401');
  await page.locator('path').click();
  await page.getByRole('button', { name: 'Sign In', exact: true }).click();
  await expect(page.getByText('Signed in successfully!')).toBeVisible();
  await page.goto('http://3.80.32.182:3000/payment-success');
  await expect(page.getByRole('heading', { name: 'Payment Success!' })).toBeVisible();
  await page.goto('chrome-error://chromewebdata/');
  await page1.goto('https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Doutlook%2Bmail%26oq%3Doutlook%2Bmail%26gs_lcrp%3DEgZjaHJvbWUyBggAEEUYOdIBCDU2NDNqMGoxqAIAsAIB%26sourceid%3Dchrome%26ie%3DUTF-8%26sei%3DlOqxZ-bGCd-d0-kP14qDyA4&q=EgRnxXAlGJTVx70GIjBqhpuQ36ZeiBHzi0HKxBLlqBQPuw4Knlev5gBrP2oI2mFBkU1vsG0oApUndztmjmgyAXJaAUM');
  await page1.locator('iframe[name="a-cahjnqspqnil"]').contentFrame().getByLabel('I\'m not a robot').click();
  await page1.locator('iframe[name="c-cahjnqspqnil"]').contentFrame().locator('td:nth-child(2)').first().click();
  await page1.locator('iframe[name="c-cahjnqspqnil"]').contentFrame().locator('tr:nth-child(2) > td').first().click();
  await page1.locator('iframe[name="c-cahjnqspqnil"]').contentFrame().locator('tr:nth-child(2) > td:nth-child(2)').click();
  await page1.locator('iframe[name="c-cahjnqspqnil"]').contentFrame().locator('td:nth-child(3)').first().click();
  await page1.locator('iframe[name="c-cahjnqspqnil"]').contentFrame().locator('tr:nth-child(3) > td:nth-child(3)').click();
  await page1.locator('iframe[name="c-cahjnqspqnil"]').contentFrame().locator('tr:nth-child(3) > td:nth-child(3)').click();
  await page1.locator('iframe[name="c-cahjnqspqnil"]').contentFrame().locator('tr:nth-child(2) > td:nth-child(3)').click();
  await page1.locator('iframe[name="c-cahjnqspqnil"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page1.locator('iframe[name="c-cahjnqspqnil"]').contentFrame().locator('tr:nth-child(2) > td:nth-child(3)').click();
  await page1.locator('iframe[name="c-cahjnqspqnil"]').contentFrame().locator('tr:nth-child(3) > td:nth-child(3)').click();
  await page1.locator('iframe[name="c-cahjnqspqnil"]').contentFrame().locator('tr:nth-child(3) > td:nth-child(2)').click();
  await page1.locator('iframe[name="c-cahjnqspqnil"]').contentFrame().locator('tr:nth-child(2) > td:nth-child(2)').click();
  await page1.locator('iframe[name="c-cahjnqspqnil"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page1.locator('iframe[name="c-cahjnqspqnil"]').contentFrame().locator('tr:nth-child(4) > td:nth-child(2)').click();
  await page1.locator('iframe[name="c-cahjnqspqnil"]').contentFrame().locator('tr:nth-child(3) > td:nth-child(2)').click();
  await page1.locator('iframe[name="c-cahjnqspqnil"]').contentFrame().locator('tr:nth-child(3) > td:nth-child(3)').click();
  await page1.locator('iframe[name="c-cahjnqspqnil"]').contentFrame().locator('tr:nth-child(2) > td:nth-child(3)').click();
  await page1.locator('iframe[name="c-cahjnqspqnil"]').contentFrame().locator('tr:nth-child(2) > td:nth-child(2)').click();
  await page1.locator('iframe[name="c-cahjnqspqnil"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page1.getByRole('link', { name: 'Microsoft Outlook (formerly' }).click();
  const page2Promise = page1.waitForEvent('popup');
  await page1.getByRole('link', { name: 'Sign in', exact: true }).click();
  const page2 = await page2Promise;
  await page2.getByTestId('i0116').click();
  await page2.getByTestId('i0116').fill('gp2_test@twilightitsolutions.com');
  await page2.getByTestId('i0116').press('Tab');
  await page2.getByTestId('signUpLink').press('Tab');
  await page2.getByRole('button', { name: 'Next' }).click();
  await page2.getByPlaceholder('Password').click();
  await page2.getByPlaceholder('Password').fill('SmartWork@1234');
  await page2.getByRole('button', { name: 'Sign in' }).click();
  await page2.getByText('Don\'t show this again').click();
  await page2.getByRole('button', { name: 'Yes' }).click();
  await page2.getByText('🎉 Welcome to HealthPointer NHF Group 12! Welcome to HealthPointer NHF Group 12').click();
  await page2.getByRole('heading', { name: '🎉 Welcome to HealthPointer NHF Group 12!', exact: true }).click();
  await page2.getByText('[https://HealthPointer NHF').click();
  await page2.getByLabel('Mark as read').click();
  await page.goto('https://healthpointernhf12.dev.goperla.com/');
  await page.getByPlaceholder('Enter your email').click();
  await page.getByPlaceholder('Enter your email').fill('gp2_test+12@twilightitsolutions.com');
  await page.getByPlaceholder('Enter your Password').click();
  await page.getByPlaceholder('Enter your Password').fill('Am@zing#Grace3401');
  await page.getByTestId('VisibilityOffIcon').click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await expect(page.getByRole('img', { name: 'logo' }).nth(1)).toBeVisible();
  await expect(page.getByRole('button', { name: 'workspace-icon    workspace_0' })).toBeVisible();
  await page.getByRole('button', { name: 'workspace-icon    workspace_0' }).getByRole('button').first().click();
  await page.getByRole('menuitem', { name: 'edit Edit' }).click();
  await page.getByTestId('close-button').click();
  await expect(page.getByRole('button', { name: 'Home' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Workspaces' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Users' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Documents' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Settings' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Create' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'search' })).toBeVisible();
  await expect(page.locator('[id="\\:rb\\:"]')).toBeVisible();
  await expect(page.locator('[id="\\:rc\\:"]')).toBeVisible();
  await expect(page.locator('[id="\\:rd\\:"]')).toBeVisible();
  await page.getByRole('button', { name: 'Create' }).click();
  await expect(page.getByRole('menuitem', { name: 'Create Workspace' })).toBeVisible();
  await expect(page.getByRole('menuitem', { name: 'Create Subsidiary' })).toBeVisible();
  await page.getByRole('menuitem', { name: 'Create Workspace' }).click();
  await expect(page.getByRole('heading', { name: 'Create Workspace' })).toBeVisible();
  await expect(page.getByText('Workspace Name *')).toBeVisible();
  await expect(page.getByPlaceholder('Enter Workspace Name')).toBeVisible();
  await expect(page.getByText('Assign Workspace to *')).toBeVisible();
  await expect(page.locator('.MuiAutocomplete-root > .MuiFormControl-root > .MuiInputBase-root')).toBeVisible();
  await expect(page.getByText('Description')).toBeVisible();
  await expect(page.getByPlaceholder('Enter Description')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Create' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Cancel' })).toBeVisible();
  await expect(page.getByTestId('close-button')).toBeVisible();
  await page.locator('.MuiAutocomplete-root > .MuiFormControl-root > .MuiInputBase-root').click();
  await expect(page.locator('.MuiAutocomplete-root > .MuiFormControl-root > .MuiInputBase-root')).toBeVisible();
  await page.getByPlaceholder('Select user').click();
  await page.getByRole('option', { name: 'gp2_test+' }).click();
  await page.getByLabel('Clear').click();
  await page.getByLabel('Open').click();
  await page.getByRole('option', { name: 'gp2_test+' }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'workspace-icon    workspace_0' }).getByRole('button').nth(1).click();
  await expect(page.getByRole('heading', { name: 'Create Subsidiary' })).toBeVisible();
  await expect(page.getByText('Subsidiary Name *')).toBeVisible();
  await expect(page.getByPlaceholder('Enter Subsidiary Name')).toBeVisible();
  await expect(page.getByText('Assign Subsidiary to')).toBeVisible();
  await expect(page.getByLabel('workspace_0')).toBeVisible();
  await expect(page.getByText('Description')).toBeVisible();
  await expect(page.getByPlaceholder('Enter Description')).toBeVisible();
  await page.getByLabel('workspace_0').click();
  await page.locator('#menu-workspace div').first().click();
  await expect(page.getByRole('button', { name: 'Create' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Cancel' })).toBeVisible();
  await page.getByTestId('close-button').click();
  await page.getByRole('button', { name: 'workspace-icon    workspace_0' }).getByRole('button').nth(1).click();
  await page.getByPlaceholder('Enter Subsidiary Name').click();
  await page.getByPlaceholder('Enter Subsidiary Name').fill('subsidiary name');
  await page.getByPlaceholder('Enter Description').click();
  await page.getByPlaceholder('Enter Description').fill('subsidiary');
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('button', { name: 'workspace-icon    workspace_0' }).click();
  await page.getByRole('button', { name: 'workspace-icon    workspace_0' }).click();
  await page.getByRole('button', { name: 'workspace-icon    workspace_0' }).getByRole('button').nth(1).click();
  await page.getByTestId('close-button').click();
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('menuitem', { name: 'Create Workspace' }).click();
  await page.getByPlaceholder('Enter Workspace Name').click();
  await page.getByPlaceholder('Enter Workspace Name').fill('worksopace_R');
  await page.getByPlaceholder('Select user').click();
  await page.getByRole('option', { name: 'gp2_test+' }).click();
  await page.getByPlaceholder('Enter Description').click();
  await page.getByPlaceholder('Enter Description').fill('Workspace_R');
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('button', { name: 'workspace-icon    worksopace_R' }).getByRole('button').nth(1).click();
  await page.getByText('Workspace created successfully').click();
  await page.getByPlaceholder('Enter Subsidiary Name').click();
  await page.getByPlaceholder('Enter Subsidiary Name').fill('subsidiary name nhf');
  await page.getByLabel('worksopace_R').click();
  await page.getByRole('option', { name: 'worksopace_R' }).click();
  await page.getByPlaceholder('Enter Description').click();
  await page.getByPlaceholder('Enter Description').fill('description subsidiary');
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('button', { name: 'workspace-icon    worksopace_R' }).click();
  await page.getByRole('button', { name: 'workspace-icon    worksopace_R' }).click();
  await page.getByRole('button', { name: 'workspace-icon    workspace_0' }).click();
  await page.getByRole('button', { name: 'workspace-icon    workspace_0' }).click();
  await page.getByRole('button', { name: 'workspace-icon    workspace_0' }).click();
  await page.locator('[id="\\:rf\\:"]').click();
  await page.getByRole('img', { name: 'logo' }).click();
  await page.locator('[id="\\:rd\\:"]').click();
  await page.getByText('Logout').click();
  await page.getByText('Logged out successfully!').click();
});